version: '3.8'

services:
  php:
    build: .
    container_name: php-app
    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx-app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
